
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__energy_proxy_hpp__PROXY_MARSHAL_H
#define __dbusxx__energy_proxy_hpp__PROXY_MARSHAL_H

#include <dbus-c++-1/dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace freedesktop {
namespace keti {
namespace bmc {

class energy_proxy
: public ::DBus::InterfaceProxy
{
public:

    energy_proxy()
    : ::DBus::InterfaceProxy("org.freedesktop.keti.bmc.energy")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    int32_t emm_ibmc()
    {
        ::DBus::CallMessage call;
        call.member("emm_ibmc");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t emm_policy()
    {
        ::DBus::CallMessage call;
        call.member("emm_policy");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t emm_feedback()
    {
        ::DBus::CallMessage call;
        call.member("emm_feedback");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t emm_monitor()
    {
        ::DBus::CallMessage call;
        call.member("emm_monitor");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }

    int32_t emm_ssp()
    {
        ::DBus::CallMessage call;
        call.member("emm_ssp");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        int32_t argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } } 
#endif //__dbusxx__energy_proxy_hpp__PROXY_MARSHAL_H
